# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

def add_user(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.rsplit('.'))
    User.objects.using(schema_editor.connection.alias).create(
        username='system',
        first_name='system',
        is_staff=True,
        protected=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user)
    ]
