# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('projects', '0002_default_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='page',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
    ]
