# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=15)),
                ('protected', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
