# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psn', models.CharField(help_text='Used as the slug in URLs.', max_length=15, unique=True, verbose_name='Short Name')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('protected', models.BooleanField(default=False, editable=False)),
                ('index_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='books.Page')),
            ],
        ),
    ]
