# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('projects', '0002_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='index_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='books.Page'),
        ),
    ]
